config/routes.rb
Rails.application.routes.draw do
  root to: 'rates#show'

  get '/u', to: 'rates#show'
  get '/admin', to: 'admin_rates#new'
  resources :admin_rates, only: :create

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rate.rb
class Rate < ApplicationRecord
  validates :value, presence: true
  validates_numericality_of :value, greater_than: 0
  validate :expiration_at_cant_be_earlier_than_now, on: :create

  default_scope { order('created_at') }

  class << self
    def forced?
      !actual_forced_last.nil?
    end

    def forced_last
      where({ forced: true }).last
    end

    def actual
      actual_forced_last || real_last
    end

    private

    def real_last
      where({ forced: false }).last
    end

    def actual_forced_last
      where({ forced: true }).where('expiration_at > ?', Time.now).last
    end
  end

  private

  # validate
  def expiration_at_cant_be_earlier_than_now
    return if expiration_at.blank? || expiration_at > Time.now

    errors.add(:expiration_at, "can't be earlier than now")
  end
end

app/controllers/admin_rates_controller.rb
class AdminRatesController < ApplicationController
  def new
    @rate = Rate.new(last_params)
  end

  def create
    @rate = DataServices::ForcedRate.create(rate_params)

    if @rate.errors.blank?
      redirect_to({ action: 'new' }, notice: "Rate #{@rate.value} was successfully created.")
    else
      render :new
    end
  end

  private

  def rate_params
    params.require(:rate).permit(:value, :expiration_at)
  end

  def last_params
    rate = Rate.forced_last
    return unless rate

    { value: rate.value, expiration_at: rate.expiration_at }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  def show
    @value = Rails.cache.fetch('actual_rate_value') do
      Rate.actual&.value
    end
  end
end

app/helpers/admin_rates_helper.rb
module AdminRatesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/admin_rates/_form.html.slim
= form_with(model: @rate, url: admin_rates_path, local: true) do |f|
  #notice = notice
  - if @rate.errors.any?
    #error_explanation
      ul
        - @rate.errors.full_messages.each do |message|
          li = message
  .form-row.text-secondary
    | Rate:
  .form-row  
    = f.number_field :value, min: 0, step: 0.0001, class: 'form-control'
  .form-row.text-secondary
    | Date:
  .form-row
    .d-flex.flex-row
      = f.date_select :expiration_at,{}, { class: 'form-control ml-1' }
  .form-row.text-secondary
    | Time:
  .form-row  
    .d-flex.flex-row
      = f.time_select :expiration_at, { :include_seconds => true, :ignore_date => true, :time_separator => '' } , { class: 'form-control ml-1' } 
  .text-center.py-4.mt-3
    = f.submit class: 'btn btn-primary'

app/views/admin_rates/new.html.slim
.card.col-11.col-md-5.col-lg-4.col-xl-3.mx-auto
  .card-body
    = render 'form'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ExchangeRate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_nav.html.slim
.navbar.navbar-expand-md.navbar-dark.bg-dark.mb-4
  button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.ml-auto
      li.nav-item = link_to 'User', u_path, class: 'nav-link'
      li.nav-item = link_to 'Admin', admin_path, class: 'nav-link'      

app/views/layouts/shared/_rate.html.slim
.d-flex.justify-content-center
  .bg-info.p-2
    | USD
    #target
      = value

app/views/rates/show.html.slim
= render 'layouts/shared/rate', :value => @value